### ISSUE TITLE
Don’t use `<footer>` without parent `<article>`, `<aside>`, `<nav>`, `<section>`

### ISSUE THREAD

**Issue by wooorm** [Murderlon/real-time-web#7]
Semantically, there’s now a footer for the `<body>`, per message.

**Comment by Murderlon** [comment]
@wooorm it is indeed not semantically correct in a `<li>`, but the `<footer>` element can be a child of any [flow content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Flow_content) element (except header en footer). So every message is not a `<footer>` for the `<body>` but a child of it's (flow content) parent.

**Comment by wooorm** [comment]
Yeah it can be in flow content, but the meaning of footers is that they apply to a sectioning root, in this case the body, so what you're saying is true, but it doesn't invalidate my point.

**Comment by Murderlon** [comment]
`<ul>` is also listed in flow content and I thought the `<footer>` applies to the first applicable parent.

**Comment by wooorm** [comment]
From the spec:

> The footer element represents a footer for its nearest ancestor sectioning content or sectioning root element. A footer typically contains information about its section such as who wrote it, links to related documents, copyright data, and the like.

Sure, you’re allowed to use it inside flow content, but that means that it’s valid to have a footer in a div in a section, and that it’s invalid to have a footer in a strong tag.

However, the whole semantics only apply to an ancestral sectioning content (article, aside, nav, section) or sectioning roots (blockquote, body, details, dialog, fieldset, figure, td)!
